menu:
  Home: /
  Archives: /archives
  Feed: /atom.xml

widgets:
- search
- tagcloud

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable:
  pubid:
  facebook:
  twitter:
  google:
  pinterest:

fancybox: true

google_analytics:
rss:

comment_provider: disqus

# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
